version: 0.2

phases:
  install:
    commands:
      - npm i -g npm
      - npm -g install typescript aws-cdk npm-check-updates
  pre_build:
    commands:
      # ABLEbase という名前で、サブモジュールとして ABLE 本体へリンクされている前提
      - cd ABLEbase
      - rm -f ./package-lock.json
      - ncu -u
      - npm cache clean --force
      - npm install
      - npm run build
  build:
    commands:
      # cdk bootstrap はすでにやっている前提
      - cdk deploy ABLE-Iam -c environment=dev --require-approval never
      # デプロイ対象を必要に応じて増やす
      # - cdk deploy ABLE-EC2App -c environment=dev --require-approval never


