# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    open-pull-requests-limit: 30
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Asia/Tokyo'
    ignore:
      - dependency-name: '@types/node'
        versions: '>=20'
      # Pin esbuild to 0.21.x because of breaking changes
      # See: https://github.com/aws/aws-cdk/pull/30726
      - dependency-name: 'esbuild'
        versions: '>=0.22'
  - package-ecosystem: 'docker' # See documentation for possible values
    directory: '/' # Location of package manifests
    open-pull-requests-limit: 30
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '08:00'
      timezone: 'Asia/Tokyo'
