queue_rules: []

pull_request_rules:
  - name: automatic merge
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be updated from
          main and then merged automatically (do not update manually, and be sure
          to [allow changes to be pushed to your 
          fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
    conditions:
      - base!=release
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge|no-squash)
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - '#approved-reviews-by>=1'
      - -approved-reviews-by~=author
      - '#changes-requested-reviews-by=0'
      - status-success=Build on Node.js v18 on ubuntu-latest
      - status-success=Build on Node.js v18 on windows-latest
      - status-success=Validate PR title
  - name: if fails conventional commits
    actions:
      comment:
        message: Title does not follow the guidelines of [Conventional Commits](https://www.conventionalcommits.org).
          Please adjust title before merge.
    conditions:
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - status-failure=Semantic PRs
      - -merged
      - -closed
  - name: automatic merge + automatic merge of Dependabot PRs
    conditions: []
    actions:
      queue:
