version: 0.2

phases:
  install:
    commands:
      - npm i -g npm
      - npm -g install typescript aws-cdk npm-check-updates
  pre_build:
    commands:
      - rm -f ./package-lock.json
      - ncu -u
      - npm cache clean --force
      - npm install
      - npm run build
  build:
    commands:
      # You can specify CDK deployment commands. Usually, you may want to deploy all of resources in the app. If you want to do so, please specify `"*"`
      - cdk deploy ABLE-GeneralLog --app "npx ts-node bin/able-guest-ecsapp-sample.ts" -c environment=dev --require-approval never
