AWSTemplateFormatVersion: "2010-09-09"
Description: 'Provides Amazon GuardDuty configuration for the AWS account'
Metadata:
    Stack:
        Value: 1
    VersionDate:
        Value: 20180420
    Identifier:
        Value: template-guardduty
    Input:
        Description: Enable or Disable
    Output:
        Description: Outputs ID of all deployed resources
Parameters:
    pEnableGuardDuty:
        Description: Specifies whether enable Amazon GuardDuty
        Type: String
        Default: false
Conditions:
    cEnableGuardDuty: !Equals [ true, !Ref pEnableGuardDuty ]
Resources:
    rGuardDutyDetector:
        Condition: cEnableGuardDuty
        Type: AWS::GuardDuty::Detector
        Properties:
            Enable: true
Outputs:
    rGuardDutyDetector:
        Condition: cEnableGuardDuty
        Value: !Ref rGuardDutyDetector