---
AWSTemplateFormatVersion: "2010-09-09"
Description: FinTech Reference Architecture for Tokyo Region - Provides nesting for required stacks to deploy
  a full sample web application with reverse proxy, ELBs, IAM, and other resources
  (for demonstration/POC/testing)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: 'Please provide the following parameter values:'
      Parameters:
      - pDBPassword
      - pNotifyEmail
      - pEC2KeyPairBastion
      - pEC2KeyPair
      - pAvailabilityZoneA
      - pAvailabilityZoneB
      - pEnableGuardDuty
    - Label:
        default: AWS FinTech Reference Architecture Configuration
      Parameters:
      - RefArchS3BucketName
      - RefArchS3KeyPrefix
    ParameterLabels:
      pDBPassword:
        default: Database Password
      pNotifyEmail:
        default: Notification Email Address
      pEC2KeyPairBastion:
        default: Existing SSH Key for the Bastion Instance
      pEC2KeyPair:
        default: Existing SSH Key for Other Instances
      pAvailabilityZoneA:
        default: First Availability Zone
      pAvailabilityZoneB:
        default: Second Availability zone
      pVPCTenancy:
        default: Instance tenancy
      pEnableGuardDuty:
        default: Amazon GuardDuty Setting
      RefArchS3BucketName:
        default: Reference Architecture S3 Bucket Name
      RefArchS3KeyPrefix:
        default: Reference Architecture S3 Key Prefix
  Stack:
    Value: 0
  VersionDate:
    Value: 20180420
  Identifier:
    Value: main
  Input:
    Description: Input of all required parameters in nested stacks
  Output:
    Description: N/A
Parameters:
  pDBPassword:
    Description: Mixed alphanumeric and must be between 8 and 28 characters and contain
      at least one capital letter
    NoEcho: true
    Type: String
    MinLength: 8
    MaxLength: 28
    AllowedPattern: '[a-zA-Z0-9!^*\-_+]*'
    ConstraintDescription: Can only contain alphanumeric characters or the following
      special characters !^*-_+, between 8 and 28 characters
  pNotifyEmail:
    Description: Notification email address for security events (you will receive
      a confirmation email)
    Type: String
    Default: to-be-notified@example.org
  pEC2KeyPairBastion:
    Description: The SSH key pair in your account to use for the bastion host login
    Type: AWS::EC2::KeyPair::KeyName
  pEC2KeyPair:
    Description: The SSH key pair in your account to use for all other EC2 instance
      logins
    Type: AWS::EC2::KeyPair::KeyName
  pAvailabilityZoneA:
    Description: Availability Zone 1
    Type: AWS::EC2::AvailabilityZone::Name
  pAvailabilityZoneB:
    Description: Availability Zone 2
    Type: AWS::EC2::AvailabilityZone::Name
  pVPCTenancy:
    Description: Instance tenancy behavior for this VPC
    Type: String
    Default: default
    AllowedValues:
    - default
    - dedicated
  pEnableGuardDuty:
    Description: Amazon GuardDuty Setting  (If you already enabled it, please specify "false")
    Type: String
    Default: false
    AllowedValues:
    - true
    - false
  RefArchS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    ConstraintDescription: Reference architecture bucket name can include numbers, lowercase
      letters, uppercase letters, periods (.), and hyphens (-). It cannot start or
      end with a hyphen (-).
    Default: fintech-reference-arch-resources
    Description: S3 bucket name for the Reference architecture assets. Reference architecture bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  RefArchS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-]+(/[0-9a-zA-Z-]+)*$
    ConstraintDescription: Reference architecture key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/). It cannot start or end
      with forward slash (/) because they are automatically appended.
    Default: templates/2018-04-20
    Description: S3 key prefix for the Reference architecture assets. Reference architecture key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/). It cannot start or end with forward slash (/) because they
      are automatically appended.
    Type: String
Mappings:
  CustomVariables:
    vResourceEnvironmentTagKey:
      Value: Environment
    vResourceEnvironmentTagValue:
      Value: development
    vRefArchS3URL:
      Value: https://s3.amazonaws.com
  InstanceConfig:
    vEC2Instance:
      AmiId: ami-28ddc154
      InstanceType: m4.large
    vRDSInstance:
      InstanceType: db.m4.large
Conditions:
  LaunchAsDedicatedInstance:
    !Equals
    - !Ref pVPCTenancy
    - dedicated
Resources:
  IamTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
        - ${RefArchS3URL}/${RefArchS3BucketName}/${RefArchS3KeyPrefix}/templates/iam.template.yaml
        - RefArchS3URL:
            !FindInMap [CustomVariables, vRefArchS3URL, Value]
      TimeoutInMinutes: 20
  LoggingTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
        - ${RefArchS3URL}/${RefArchS3BucketName}/${RefArchS3KeyPrefix}/templates/logging.template.yaml
        - RefArchS3URL:
            !FindInMap [CustomVariables, vRefArchS3URL, Value]
      TimeoutInMinutes: 20
      Parameters:
        pNotifyEmail: !Ref pNotifyEmail
  GuardDutyTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
        - ${RefArchS3URL}/${RefArchS3BucketName}/${RefArchS3KeyPrefix}/templates/guardduty.template.yaml
        - RefArchS3URL:
            !FindInMap [CustomVariables, vRefArchS3URL, Value]
      TimeoutInMinutes: 20
      Parameters:
        pEnableGuardDuty: !Ref pEnableGuardDuty
  ProductionVpcTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
        - ${RefArchS3URL}/${RefArchS3BucketName}/${RefArchS3KeyPrefix}/templates/vpc-production.template.yaml
        - RefArchS3URL:
            !FindInMap [CustomVariables, vRefArchS3URL, Value]
      TimeoutInMinutes: 20
      Parameters:
        pRegionAZ1Name: !Ref pAvailabilityZoneA
        pRegionAZ2Name: !Ref pAvailabilityZoneB
        pProductionVPCName: Production VPC
        pBastionSSHCIDR: 0.0.0.0/0
        pDMZSubnetACIDR: 10.100.10.0/24
        pDMZSubnetBCIDR: 10.100.20.0/24
        pManagementCIDR: 10.10.0.0/16
        pAppPrivateSubnetACIDR: 10.100.96.0/21
        pAppPrivateSubnetBCIDR: 10.100.119.0/21
        pDBPrivateSubnetACIDR: 10.100.194.0/21
        pDBPrivateSubnetBCIDR: 10.100.212.0/21
        pVPCTenancy: !Ref pVPCTenancy
        pEnvironment:
          !FindInMap [CustomVariables, vResourceEnvironmentTagValue, Value]
        pEC2KeyPair: !Ref pEC2KeyPair
  ManagementVpcTemplate:
    Type: AWS::CloudFormation::Stack
    DependsOn: ProductionVpcTemplate
    Properties:
      TemplateURL:
        !Sub
        - ${RefArchS3URL}/${RefArchS3BucketName}/${RefArchS3KeyPrefix}/templates/vpc-management.template.yaml
        - RefArchS3URL:
            !FindInMap [CustomVariables, vRefArchS3URL, Value]
      TimeoutInMinutes: 20
      Parameters:
        pProductionVPC:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rVPCProduction
        pRouteTableProdPrivate:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rRouteTableProdPrivate
        pRouteTableProdPublic:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rRouteTableProdPublic
        pProductionCIDR: 10.100.0.0/16
        pBastionSSHCIDR: 0.0.0.0/0
        pManagementCIDR: 10.10.0.0/16
        pManagementDMZSubnetACIDR: 10.10.1.0/24
        pManagementDMZSubnetBCIDR: 10.10.2.0/24
        pManagementPrivateSubnetACIDR: 10.10.20.0/24
        pManagementPrivateSubnetBCIDR: 10.10.30.0/24
        pManagementVPCName: Management VPC
        pEC2KeyPairBastion: !Ref pEC2KeyPairBastion
        pEC2KeyPair: !Ref pEC2KeyPair
        pVPCTenancy: !Ref pVPCTenancy
        pBastionAmi:
          !FindInMap [InstanceConfig, vEC2Instance, AmiId]
        pRegionAZ1Name: !Ref pAvailabilityZoneA
        pRegionAZ2Name: !Ref pAvailabilityZoneB
        pEnvironment:
          !FindInMap [CustomVariables, vResourceEnvironmentTagValue, Value]
        pBastionInstanceType:
          !If
          - LaunchAsDedicatedInstance
          - m4.large
          - t2.small
  ConfigRulesTemplate:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - IamTemplate
    - ProductionVpcTemplate
    - ManagementVpcTemplate
    - LoggingTemplate
    Properties:
      TemplateURL:
        !Sub
        - ${RefArchS3URL}/${RefArchS3BucketName}/${RefArchS3KeyPrefix}/templates/config-rules.template.yaml
        - RefArchS3URL:
            !FindInMap [CustomVariables, vRefArchS3URL, Value]
      TimeoutInMinutes: 20
      Parameters:
        pRequiredTagKey:
          !FindInMap [CustomVariables, vResourceEnvironmentTagKey, Value]
  ApplicationTemplate:
    Type: AWS::CloudFormation::Stack
    DependsOn:
    - IamTemplate
    - ProductionVpcTemplate
    Properties:
      TemplateURL:
        !Sub
        - ${RefArchS3URL}/${RefArchS3BucketName}/${RefArchS3KeyPrefix}/templates/application.template.yaml
        - RefArchS3URL:
            !FindInMap [CustomVariables, vRefArchS3URL, Value]
      TimeoutInMinutes: 30
      Parameters:
        pSecurityAlarmTopic:
          !GetAtt
          - LoggingTemplate
          - Outputs.rSecurityAlarmTopic
        pEC2KeyPair: !Ref pEC2KeyPair
        pProductionCIDR: 10.100.0.0/16
        pProductionVPC:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rVPCProduction
        pDMZSubnetA:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rDMZSubnetA
        pDMZSubnetB:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rDMZSubnetB
        pAppPrivateSubnetA:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rAppPrivateSubnetA
        pAppPrivateSubnetB:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rAppPrivateSubnetB
        pWebInstanceType:
          !FindInMap
          - InstanceConfig
          - vEC2Instance
          - InstanceType
        pAppInstanceType:
          !FindInMap
          - InstanceConfig
          - vEC2Instance
          - InstanceType
        pDBPrivateSubnetA:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rDBPrivateSubnetA
        pDBPrivateSubnetB:
          !GetAtt
          - ProductionVpcTemplate
          - Outputs.rDBPrivateSubnetB
        pManagementCIDR: 10.10.0.0/16
        pRegionAZ1Name: !Ref pAvailabilityZoneA
        pRegionAZ2Name: !Ref pAvailabilityZoneB
        pWebServerAMI:
          !FindInMap
          - InstanceConfig
          - vEC2Instance
          - AmiId
        pAppAmi:
          !FindInMap
          - InstanceConfig
          - vEC2Instance
          - AmiId
        pDBUser: testuserdb
        pDBName: testDB
        pDBPassword: !Ref pDBPassword
        pDBClass:
          !FindInMap
          - InstanceConfig
          - vRDSInstance
          - InstanceType
        pDBAllocatedStorage: "10"
        pEnvironment:
          !FindInMap
          - CustomVariables
          - vResourceEnvironmentTagValue
          - Value
        pBastionSSHCIDR: 0.0.0.0/0
        RefArchS3URL:
          !FindInMap [CustomVariables, vRefArchS3URL, Value]
        RefArchS3BucketName: !Ref RefArchS3BucketName
        RefArchS3KeyPrefix: !Ref RefArchS3KeyPrefix
Outputs:
  TemplateType:
    Value: Standard Multi-Tier Web Application
  TemplateVersion:
    Value: 1.0
  BastionIP:
    Description: Use this IP via SSH to connect to Bastion Instance
    Value:
      !GetAtt
      - ManagementVpcTemplate
      - Outputs.rBastionInstanceIP
  LandingPageURL:
    Value:
      !GetAtt
      - ApplicationTemplate
      - Outputs.LandingPageURL
  WebsiteURL:
    Value:
      !GetAtt
      - ApplicationTemplate
      - Outputs.WebsiteURL
